(define (element-of-set? element set)
  (cond ((null? set) false)
	((equal? (car set) element) true)
	(else (element-of-set? element (cdr set)))))

(define (adjoin-set element set)
  (if (element-of-set? element set)
      set
      (cons element set)))

(define (intersection-set set1 set2)
  (cond ((or (null? set1) (null? set2)) '())
	((element-of-set? (car set1) set2)
	 (cons (car set1)
	       (intersection-set (cdr set1)
				 set2)))
	(else (intersection-set (cdr set1)
				set2))))

(define (union-set set1 set2)
  (cond ((null? set1) set2)
	((null? set2) set1)
	((not (element-of-set? (car set1) set2))
	 (cons (car set1)
	       (union-set (cdr set1)
			  set2)))
	(else (union-set (cdr set1)
			 set2))))
